### ISSUE TITLE
Swap A/B with Left/Right

### ISSUE THREAD

**Issue by mvdan** [pkg/diff#1]
Are the names `A` and `B` common in diff algorithms or APIs? I would personally find `Left` and `Right` more intuitive. Diffs are very commonly displayed like this - some use `<` and `>` to display "removed" and "added", lots of code review UIs do side-by-side reviews, et cetera.

The names are also short enough to be spelled out in parameter names, avoiding the confusion of `r` with `io.Reader`.

**Comment by josharian** [comment]
I'm not sure how common they are, but the fact that they are short and used consistently is helpful. E.g. I think `Equal(ai, bi int) bool` reads better than `Equal(li, ri int) bool`. `Equal(leftIdx, rightIdx int) bool` might be better. And being able to call things `ab` is nice. The fact that they align nicely also satisfies my OCD. I experimented with a few different naming schemings when using this as part of a larger project and settled on `ab` as something I could use throughout.

But if you think I'm making a serious mistake, I'm open to more discussion.

**Comment by mvdan** [comment]
You're right, there's a tradeoff here. My initial confusion was fixed after just a minute of looking around and reading, so I think it's fine.
