### ISSUE TITLE
Writeable is confusing

### ISSUE THREAD

**Issue by mvdan** [pkg/diff#6]
I initially read `WriteToA` as "write to A", not as "write A to ...".

Assuming #1 is done, we could rewrite this to:

```
type Writeable interface {
    LeftWriteTo(w io.Writer, i int) (int, error)
    RightWriteTo(w io.Writer, i int) (int, error)
    LeftFilename() string
    RightFilename() string
}
```

**Comment by josharian** [comment]
What do you think about:

```go
type Writeable interface {
	WriteATo(w io.Writer, i int) (int, error)
	WriteBTo(w io.Writer, i int) (int, error)
	FilenameA() string
	FilenameB() string
}
```

**Comment by josharian** [comment]
Also, I see that the docs for Writeable are woefully inadequate: The role of `i`  is completely unexplained.

**Comment by mvdan** [comment]
WriteXTo instead of WriteToX sounds fine to me.
